Release/v1.2.6
coopdevs/backups-role pull request #39
Opened 2020-01-22 17:10 UTC by raneq

## [v1.2.6] - 2020-01-23
### Changed
- Fix: when using default backups-prepare script, manage the case when no assets_paths are defined.
  See [#38](https://github.com/coopdevs/backups_role/pull/38)

2020-01-22 17:11 UTC, raneq commented
We will need this soon when provisioning again timeoverflow.

2020-01-22 18:12 UTC, sauloperez requested changes

2020-01-22 18:12 UTC, sauloperez commented on CHANGELOG.md
> +- Fix: when using default backups-prepare script, manage the case when no assets_paths are defined.
I would rather list it under a `Fixed` category as described in `Types of changes` at https://keepachangelog.com/en/1.0.0/.

It is rather conmon to search known issues in the changelog to see which version fixed it and this makes it easier.

2020-01-23 08:30 UTC, sauloperez approved these changes

2020-01-23 10:51 UTC, merged